### PR TITLE
Fix isOn() for float values

### LINKED ISSUE #29: [Bug] isOn() does not return true for truthy Float values
There is a bug that when using a float value, `isOn()` is not true.

`isOn()` should return true for all non-zero float values.

### PR DESCRIPTION
**Pull request by tinahollygb**
fixes #29 check for instance of Double in FeatureResult#isOn()

### CODE REVIEW

File: lib/src/test/java/growthbook/sdk/java/FeatureResultTest.java [hunk 1]
```diff
@@ -62,4 +61,110 @@ void featureResultSourceOutputsCorrectlyToJson() {
...
+    void featureResult_isOn_withNonZeroValue_returnsTrue_forDoubles() {
+        FeatureResult<Double> subject = FeatureResult
+            .<Double>builder()
+            .value(1.0)
+            .source(FeatureResultSource.FORCE)
+            .build();
+
+        assertTrue(subject.isOn());
+        assertFalse(subject.isOff());
+    }
```
Comment (tinahollygb) [inline lib/src/test/java/growthbook/sdk/java/FeatureResultTest.java:129]: This is the test case that would fail.
